version: '3'  # Указывает версию формата файла Docker Compose (в данном случае версия 3)

services:
  app:  # Описание сервиса с именем "app"
    build:  # Настройки для создания Docker-образа
      context: ./  # Контекст сборки - текущая директория, где находится Dockerfile
      dockerfile: Dockerfile  # Указывает на файл Dockerfile, который будет использоваться для сборки образа
    volumes:
      - ./:/var/www/html/  # Монтирование текущей директории (где находится docker-compose.yml) в контейнер на путь /var/www/html/
    ports:
      - "5001:80"  # Проброс порта: порт 5000 на хосте будет перенаправлен на порт 80 внутри контейнера
